### ISSUE TITLE
[Bug] doesn't work because of the addition of negative prompt

### ISSUE THREAD

**Issue by kookiny** [lkwq007/stablediffusion-infinity#58]
it worked until yesterday but doesn't work anymore because of the Negative Prompt
I haven't seen Negative Prompt thing until yesterday but it poped up and it returns error about it

```
 File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
TypeError: __call__() got an unexpected keyword argument 'negative_prompt'

```

![image](https://user-images.githubusercontent.com/5319368/194685395-107904ed-4d68-4a7a-83f0-c4b566d2106f.png)

**Comment by lkwq007** [comment]
Please upgrade `diffusers` to `0.4.0`.

**Comment by lkwq007** [comment]
A fallback is added. Now it also works with `diffusers` 0.3.0
